### ISSUE TITLE
Error trying to get Tuple of tensor with NewIValue

### ISSUE THREAD

**Issue by mauriciocm9** [sugarme/gotch#38] opened 2021-06-02 14:44 UTC
Hi, i'm trying to convert 2 tensors into a tuple. However when i try to use `ts.NewIValue([]ts.IValue{tensora, tensorb})` i'm getting this error: `NewIValue method call - 'slice -> struct' case - Unsupported type (slice)`. I managed to make it work by editing `tensor/jit.go` file in the line 90 with:
```
switch reflect.TypeOf(v).Elem().String() {
case "tensor.IValue":
```

Is this something that should be fixed? or i'm using `NewIValue` incorrectly?

**Comment by sugarme** [comment] 2021-06-03 01:27
Hi @mauriciocm9 ,

I could not reproduce the issue that you had. 

```go

package main

import (
	"fmt"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
)

func main() {
	tensorA := ts.MustOnes([]int64{2, 2}, gotch.Float, gotch.CPU)
	tensorB := ts.MustZeros([]int64{2, 2}, gotch.Float, gotch.CPU)

	input := ts.NewIValue([]ts.Tensor{*tensorA, *tensorB})

	fmt.Printf("%v\n", input)
}
// output:
// &{[{{0x251a6c0} {0x60a3e0} Tensor} {{0x251a820} {0x60a3e0} Tensor}] {0x600f20} TensorList}

```

My box version:
- go version go1.16.2 linux/amd64
- **gotch version: v0.3.9**

What gotch version are you using at your end?

**Comment by mauriciocm9** [comment] 2021-06-03 02:25
yes, thank you, that works i was converting tensorA and tensorB to IValue. Now i'm facing an issue when using ForwardIs `panic: interface conversion: interface {} is []tensor.IValue, not []tensor.Tensor`. What i'm trying to do, is feed a Tuple[Tensor, Tensor] to a model using CModule

**Comment by sugarme** [comment] 2021-06-03 02:33
@mauriciocm9 ,

Would you mind giving a simplified example that causes the panic?

**Comment by mauriciocm9** [comment] 2021-06-03 02:49
```
package main

import (
	"log"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
)

func main() {
	model, err := ts.ModuleLoad("torchtest/modelito.pt")
	if err != nil {
		println("Failed module load")
		log.Fatal(err)
	}

	tensorA := ts.MustOnes([]int64{2, 2}, gotch.Float, gotch.CPU)
	tensorB := ts.MustZeros([]int64{2, 2}, gotch.Float, gotch.CPU)

	input := ts.NewIValue([]ts.Tensor{*tensorA, *tensorB})

	output, err := model.ForwardIs([]ts.IValue{*input})
	if err != nil {
		println("error in forward", err.Error())
	}

	println(output)
}
```
Any model can work here since this happens before AtmForward

**Comment by sugarme** [comment] 2021-06-03 02:56
Can you paste the panic log please?

**Comment by mauriciocm9** [comment] 2021-06-03 02:58
```
panic: interface conversion: interface {} is []tensor.IValue, not []tensor.Tensor

goroutine 1 [running]:
github.com/sugarme/gotch/tensor.(*IValue).ToCIValue(0xc000050e70, 0x6314c0, 0xc000050df8, 0x6314c0)
	/home/truora/go/pkg/mod/github.com/sugarme/gotch@v0.3.9/tensor/jit.go:337 +0x2ee5
github.com/sugarme/gotch/tensor.(*CModule).ForwardIs(0xc0000b2040, 0xc000105f48, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/truora/go/pkg/mod/github.com/sugarme/gotch@v0.3.9/tensor/jit.go:1070 +0x3a5
main.main()
	/home/truora/go/src/bitbucket.org/truora/scrap-services/main.go:22 +0x265
exit status 2
```

**Comment by sugarme** [comment] 2021-06-03 03:19
@mauriciocm9 

I can reproduce the panic now.  Seem to be type casting here. Does this way work for you?
```go
import (
	"log"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
)

func main() {
	model, err := ts.ModuleLoad("torchtest/modelito.pt")
	if err != nil {
		println("Failed module load")
		log.Fatal(err)
	}

	tensorA := ts.MustOnes([]int64{2, 2}, gotch.Float, gotch.CPU)
	tensorB := ts.MustZeros([]int64{2, 2}, gotch.Float, gotch.CPU)
	ivalueA := ts.NewIValue(*tensorA)
	ivalueB := ts.NewIValue(*tensorB)

	output, err := model.ForwardIs([]ts.IValue{*ivalueA, *ivalueB})
	if err != nil {
		println("error in forward", err.Error())
	}

	println(output)

}

```

Or you can try with `ForwardTs`?

**Comment by mauriciocm9** [comment] 2021-06-03 03:25
i already tried both options, the models seem to only accept a tuple of tensors, the only way its works for me is:
```go
package main

import (
	"log"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
)

func main() {
	model, err := ts.ModuleLoad("torchtest/modelito.pt")
	if err != nil {
		println("Failed module load")
		log.Fatal(err)
	}

	tensorA := ts.MustOnes([]int64{2, 2}, gotch.Float, gotch.CPU)
	tensorB := ts.MustZeros([]int64{2, 2}, gotch.Float, gotch.CPU)
	ivalueA := ts.NewIValue(*tensorA)
	ivalueB := ts.NewIValue(*tensorB)

	tupleOfTensor := ts.NewIValue([]ts.IValue{*ivalueA, *ivalueB})

	output, err := model.ForwardIs([]ts.IValue{*tupleOfTensor})
	if err != nil {
		println("error in forward", err.Error())
	}

	println(output)

}
```
But as mentioned in the issue, i had to edit jit.go:
```go
case "slice": // line 91
  switch reflect.TypeOf(v).Elem().String() {
  case "tensor.IValue":

```

**Comment by sugarme** [comment] 2021-06-03 05:16
Hi @mauriciocm9 ,

I have tried to fix the issue in branch `jit`. Can you test it by updating gotch to `jit` branch:
```bash
go get -u github.com/sugarme/gotch@jit
```

and try the previous code : (you might have to change the tensor input shape and type according to your model requirement).

```go
package main

import (
	"log"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
)

func main() {
	model, err := ts.ModuleLoad("torchtest/modelito.pt")
	if err != nil {
		println("Failed module load")
		log.Fatal(err)
	}

       // NOTE. change tensor shape and type here according to your model requirement
	tensorA := ts.MustOnes([]int64{2, 2}, gotch.Float, gotch.CPU)
	tensorB := ts.MustZeros([]int64{2, 2}, gotch.Float, gotch.CPU)

	input := ts.NewIValue([]ts.Tensor{*tensorA, *tensorB})

	output, err := model.ForwardIs([]ts.IValue{*input})
	if err != nil {
		println("error in forward", err.Error())
	}

	println(output)
}
```

Let me know how you go, thanks.

**Comment by mauriciocm9** [comment] 2021-06-04 00:35
yes, it works

**Comment by sugarme** [comment] 2021-06-04 01:16
@mauriciocm9 , 
Thanks for your feedback. I am closing the issue for now. Will merge in the next release.

**Closed by sugarme** 2021-06-04 01:16 UTC
Labels: bug
