### ISSUE TITLE
Simple code consumes all memory in seconds

### ISSUE THREAD

**Issue by Claus1** [sugarme/gotch#23] opened 2021-04-07 16:35 UTC
I analyze my photos in a cycle by calling the func :
```
func CalcProbs(imageFile string, model *ts.CModule, k int64 ) []TopItem {
	//runtime.GC()
	// Load the image file and resize it to the usual imagenet dimension of 224x224.
	image, err := imageNet.LoadImageAndResize224(imageFile)
	if err != nil {
		log.Fatal(err, imageFile)
	}
	// Apply the forward pass of the model to get the logits.
	output := image.MustUnsqueeze(int64(0), false).ApplyCModule(model).MustSoftmax(-1, gotch.Float, true)

	return Top(output, k)	
}
```

Photo size for all not more than 1 MB. After 50 calls it consumes all free memory ~26 GB. Manual calls runtime.GC() don't help. What it can be?
In Python a bit different code works OK for thousands photos..

**Comment by sugarme** [comment] 2021-04-08 00:05
Hi @Claus1 ,

What you described is memory blow up. It is likely caused by left-over intermediate tensors. As `gotch` connects the 2 lands (Go and C lands) using `unsafe.Pointer` so `runtime.GC()` may not be helpful and we have to free up memory by ourselves. `gotch` provides methods to delete tensor and free up C memory: `tensor.Drop()` and `tensor.MustDrop()`. 

There are some points to keep in mind while working with gotch that I found useful:
- Gotch APIs are quite similar to Pytorch C++ in a sense that calling a tensor method will create another tensor except for **in-place** methods. Hence, if you don't use the previous tensor, after calling a method on it, the tensor should be deleted to free up memory.
- Chaining methods are hidden trap of leaving intermediate tensors behind. So in debugging mode, I would break them down to seperate method calls and delete intermediate tensors after method call. And make sure to delete the last intermediate tensor before function return as well. 

From your above code, some points I would dig in:
- `output := image.MustUnsqueeze(int64(0), false).ApplyCModule(model).MustSoftmax(-1, gotch.Float, true)`:
```go
	img := image.MustUnsqueeze(int64(0), true) // delete intermediate image tensor if you don't intend to use it lately
	imgFw := img.ApplyCModule(model)
	img.MustDrop() // delete img tensor
	output := img.MustSoftmax(-1, gotch.Float, true) // ok here as true will delete img after method call.	
```
- `return Top(output, k)` should be debugged as well. Also, before ending up function, all intermediate tensors created inside the function need to be deleted otherwise, it will stay in **C memory** and Go garbage collector will never know. So here, I would do:
```go
	topResult := Top(output, k)
	output.MustDrop() // delete this tensor before leaving function
	return topResult
``` 
-  Also, it could be an issue inside the gotch `ApplyCModule` as well. I haven't tested this function throughoutly so please let me know if you find something in there. 

Lastly, there is a example in `example/debug-memory` in `gotch` showing how to deal with memory blow up. It migh be helpful.

Feel free to discuss further.

**Comment by Claus1** [comment] 2021-04-08 05:50
I found in the code 
```
img := image.MustUnsqueeze(int64(0), true) // delete intermediate image tensor if you don't intend to use it lately
imgFw := img.ApplyCModule(model)
img.MustDrop() // delete img tensor	
output := imgFw.MustSoftmax(-1, gotch.Float, true) 
//imgFw.MustDrop()
```
The last MustDrop causes fault if uncommented.

In the code
```
func Top(input *ts.Tensor, k int64) []TopItem {

	var tensor *ts.Tensor
	shape := input.MustSize()	
	tensor = input.MustView([]int64{shape[1]}, false) // shape: [1000]
	
	valsTs, idxsTs := tensor.MustTopK(k, 0, true, true)

	var topItems []TopItem

	vals := valsTs.Float64Values()
	idxs := idxsTs.Float64Values()

	for i := 0; i < int(k); i++ {
		val := vals[i]
		idx := idxs[i]

		item := TopItem{
			prob: val,
			class:  int(idx),
		}
		topItems = append(topItems, item)
	}
	//valsTs.MustDrop()
	idxsTs.MustDrop()
	tensor.MustDrop()

	return topItems
}
```
uncommented valsTs.MustDrop() causes fault.

Anyway even after that changes the memory leaks almost with the same speed.

**Comment by sugarme** [comment] 2021-04-08 06:10
Hi @Claus1 ,

Have you tried to delete `output` as I mentioned before?
```go

	topResult := Top(output, k)
	output.MustDrop() // delete this tensor before leaving function
	return topResult

```

Also, I would suggest setting up a mock-up running to debug memory leak as in [example/debug-memory](https://github.com/sugarme/gotch/tree/master/example/debug-memory). You can set up a for-loop to forward pass the model and see where the memory blowing up.

If you can share more code or `model` I can try on my end.

**Comment by Claus1** [comment] 2021-04-08 06:26
Hi @sugarme, I tried output.MustDrop() inside Top(), it doesn't help.
My all code:
```
func main() {	
	top := 0
	top10 := 0
	total := 0
	//CalcProbs(testFile, modelDerma, 10)
	for i, dis := range disImageArr{
		total += 1
		for _, fn := range dis2Images[dis.name]{
			probs := CalcProbs(fn, modelDerma, 10)
			if  i == probs[0].class {
				top += 1
			} else {
				for _, prob := range probs{
					if prob.class == i{
						top10 += 1
					}
				}
			}
		}
	}
	print(total, top, top10)
}
```
the model can by any, I used https://drive.google.com/file/d/1-5Bhngf535Wpbh6mgnh8jAO1TIhGoNba/view?usp=sharing

```
var (
	modelPath = "derma.pt"
	imageNet = vision.NewImageNet()
	modelDerma *ts.CModule
)

type TopItem struct {
	prob float64
	class  int
}

func init() {
	// Load the Python saved module.
	model, err := ts.ModuleLoad(modelPath)
	if err != nil {
		log.Fatal(err)
		return
	}
	modelDerma = model
}
```


and previous
```
func Top(input *ts.Tensor, k int64) []TopItem {

	var tensor *ts.Tensor
	shape := input.MustSize()
	
	tensor = input.MustView([]int64{shape[1]}, false) // shape: [1000]
	
	valsTs, idxsTs := tensor.MustTopK(k, 0, true, true)

	var topItems []TopItem

	vals := valsTs.Float64Values()
	idxs := idxsTs.Float64Values()

	for i := 0; i < int(k); i++ {
		val := vals[i]
		idx := idxs[i]

		item := TopItem{
			prob: val,
			class:  int(idx),
		}
		topItems = append(topItems, item)
	}
	//valsTs.MustDrop()
	idxsTs.MustDrop()
	tensor.MustDrop()
	input.MustDrop() // delete this tensor before leaving function

	return topItems
}

func CalcProbs(imageFile string, model *ts.CModule, k int64 ) []TopItem {
	//runtime.GC()
	// Load the image file and resize it to the usual imagenet dimension of 224x224.
	image, err := imageNet.LoadImageAndResize224(imageFile)
	if err != nil {
		log.Fatal(err, imageFile)
	}
	// Apply the forward pass of the model to get the logits.
	img := image.MustUnsqueeze(int64(0), true) // delete intermediate image tensor if you don't intend to use it lately
	imgFw := img.ApplyCModule(model)
	img.MustDrop() // delete img tensor	
	output := imgFw.MustSoftmax(-1, gotch.Float, true) 
	//imgFw.MustDrop()
	
	image.MustDrop()
	
	topResult := Top(output, k)	
	return topResult
}
```

**Comment by sugarme** [comment] 2021-04-08 07:07
Hi @Claus1 

I tried to setup a for-loop to run for 1000 times same image without any problem. Please have a look. 

```go
package main

import (
	"fmt"
	"log"

	"github.com/sugarme/gotch"
	ts "github.com/sugarme/gotch/tensor"
	"github.com/sugarme/gotch/vision"
)

type TopItem struct {
	prob  float64
	class int
}

func main() {
	model, err := ts.ModuleLoad("./derma.pt")
	if err != nil {
		log.Fatal(err)
	}

	imageNet := vision.NewImageNet()
	image, err := imageNet.LoadImageAndResize224("./sample.jpg")
	if err != nil {
		log.Fatal(err)
	}

	for i := 0; i < 1000; i++ {
		fmt.Printf("Processed %v...\n", i)
		img := image.MustUnsqueeze(int64(0), false)
		imgFw := img.ApplyCModule(model)
		img.MustDrop()
		output := imgFw.MustSoftmax(-1, gotch.Float, true)
		topResult := Top(output, 5)
		fmt.Printf("%+v\n", topResult)
		output.MustDrop()
	}
}

func Top(input *ts.Tensor, k int64) []TopItem {
	var tensor *ts.Tensor
	shape := input.MustSize()
	tensor = input.MustView([]int64{shape[1]}, false) // shape: [1000]
	valsTs, idxsTs := tensor.MustTopK(k, 0, true, true)
	var topItems []TopItem
	vals := valsTs.Float64Values()
	idxs := idxsTs.Float64Values()

	for i := 0; i < int(k); i++ {
		val := vals[i]
		idx := idxs[i]

		item := TopItem{
			prob:  val,
			class: int(idx),
		}
		topItems = append(topItems, item)
	}

	valsTs.MustDrop()
	idxsTs.MustDrop()
	tensor.MustDrop()

	return topItems
}

```

From your code, I think you might need to 
1. Load model 1 time
2. Do not delete input tensor. Just delete **intermediate** tensors.

Let me know how you go with that.

**Comment by Claus1** [comment] 2021-04-08 09:04
Hi @sugarme ! Thanks! I changed your code for analyzing different  and leaks anyway but much less) although I drop the  image tensor at the end. 
```
for _,dis := range disImageArr{
		total += 1
		for _, fn := range dis2Images[dis.name]{			
			image, err := imageNet.LoadImageAndResize224(fn)
			if err != nil {
				log.Fatal(err)
			}			
			img := image.MustUnsqueeze(int64(0), false)
			imgFw := img.ApplyCModule(modelDerma)
			img.MustDrop()
			output := imgFw.MustSoftmax(-1, gotch.Float, true)
			topResult := Top(output, 10)
			fmt.Printf("%+v\n", topResult)
			image.MustDrop()
			output.MustDrop()
		}
	}
```

**Comment by sugarme** [comment] 2021-04-08 09:28
@Claus1 ,

You should delete `image` as you don't reuse it as in my previous code. So replace `false` with `true` in `image.MustUnsqueeze()` method.

```go
for _,dis := range disImageArr{
		total += 1
		for _, fn := range dis2Images[dis.name]{			
			image, err := imageNet.LoadImageAndResize224(fn)
			if err != nil {
				log.Fatal(err)
			}			
			img := image.MustUnsqueeze(int64(0), true) // <----------- Delete this intermediate tensor. In previous code I use it in for-loop so would not delete it here.
			imgFw := img.ApplyCModule(modelDerma)
			img.MustDrop()
			output := imgFw.MustSoftmax(-1, gotch.Float, true)
			topResult := Top(output, 10)
			fmt.Printf("%+v\n", topResult)
			image.MustDrop()
			output.MustDrop()
		}
	}
```

**Comment by sugarme** [comment] 2021-04-08 11:49
@Claus1 ,

Your code looks okay for me. I tried to run through ~ 2000 real images without any problem. If you look at the memory usage, it does grow up but that is because of Go concurrency in for-loop and I would not consider it as memory leak. For 2000 images in such for-loop, my machine used up ~ 3GiB of RAM and all freed up after for-loop completed.

**Comment by Claus1** [comment] 2021-04-08 11:54
Thanks a lot. Now it works ok. Can you think about tensor's autodrop? Easy to make mistakes)

**Comment by sugarme** [comment] 2021-04-08 12:00
@Claus1 ,

Tensor autodrop would be a great feature, however, I haven't had a concrete idea yet. Feel free to contribute.
If you okay with the code, please close this issue for now. Further discussion can be posted on github discussion.

**Closed** 2021-04-08 12:01 UTC
Labels: bug

**Comment by Claus1** [comment] 2021-04-08 12:44
> For 2000 images in such for-loop, my machine used up ~ 3GiB of RAM and all freed up after for-loop completed.

FYI I run on 2200 images it consumes 3.2 GB during the cycle but nothing fried up even after 15 min waiting (http server was idle).

**Comment by isdzulqor** [comment] 2021-07-25 10:46
> > For 2000 images in such for-loop, my machine used up ~ 3GiB of RAM and all freed up after for-loop completed.
> 
> FYI I run on 2200 images it consumes 3.2 GB during the cycle but nothing freed up even after 15 min waiting (http server was idle).

I'm also experiencing this memory blow-up issue using libtorch with CPU. memory deallocation is not working well. have did MustDrop in the tensors related.

**Comment by StrongerXi** [comment] 2022-11-26 05:16
Hi @sugarme. I ran into the same issue here, and I found [this](https://github.com/orktes/go-torch/blob/e0f5fdb973e83cb52df819205454f6d30359d2d2/tensor.go#L53) from a similar project. It seems like we could just add `MustDrop` as the finalizer for tensor objects?

**Comment by sugarme** [comment] 2022-11-28 03:06
@StrongerXi,

I have never had Go runtime GC works properly with gotch. I chose manually memory management though calling `ts.Drop()` multiple times is painful but it seems to be stable and reliable.  See the discussion below:

https://groups.google.com/g/golang-nuts/c/Hd0uPrKIDww

It would be a great improvement if we could have this feature. Would you mind to help out with setting up a testing? Thanks.

**Comment by StrongerXi** [comment] 2022-11-28 03:17
Thanks for the context. I'd love to contribute but I don't have enough bandwidth atm... But `Drop` isn't too bad, I can still make it work for my use case.
