### ISSUE TITLE
Libtorch_cpu.so MKL linking error

### ISSUE THREAD

**Issue by ceo-domido** [sugarme/gotch#64] opened 2021-12-23 22:20 UTC
I have created a Docker file to deploy gotcha and run the simplified convolutional neural network in a container but found a linking error:
```FROM ubuntu
RUN apt-get -y update
RUN apt-get -y install apt-utils
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get -y install wget sudo unzip git intel-mkl-full cmake golang
ENV LIBTORCH_PATH="/usr/local/lib"
ENV GOTCH_LIBTORCH="$LIBTORCH_PATH/libtorch"
ENV LIBRARY_PATH="$LIBRARY_PATH:$GOTCH_LIBTORCH/lib:/usr/lib/x86_64-linux-gnu/mkl"
ENV CPATH="$CPATH:$GOTCH_LIBTORCH/lib:$GOTCH_LIBTORCH/include:$GOTCH_LIBTORCH/include/torch/csrc/api/include:/usr/include"
ENV GOPATH="/root/go"
#
# THE CODE BELOW DO NOT WORK BECAUSE OF SOME ERRORS IN setup-libtorch.sh
# RUN wget https://raw.githubusercontent.com/sugarme/gotch/master/setup-libtorch.sh \
#    && chmod +x setup-libtorch.sh \
#    && export CUDA_VER=cpu && bash setup-libtorch.sh
#
# This code works
RUN export LIBTORCH_ZIP="libtorch-cxx11-abi-shared-with-deps-1.10.0%2Bcpu.zip" \
    && wget  -q --show-progress --progress=bar:force:noscroll  -O "/tmp/$LIBTORCH_ZIP" "https://download.pytorch.org/libtorch/cpu/$LIBTORCH_ZIP" \
    && unzip "/tmp/$LIBTORCH_ZIP" -d $LIBTORCH_PATH \
    && rm "/tmp/$LIBTORCH_ZIP" \
    && ldconfig
#
# Option 1. DO NOT WORK
# main.go:5:2: no Go files in /root/go/src/github.com/sugarme/gotch
#
#RUN wget https://raw.githubusercontent.com/sugarme/gotch/master/setup-gotch.sh
#RUN chmod +x setup-gotch.sh
#RUN export CUDA_VER=cpu && export GOTCH_VER=v0.5.0 && bash setup-gotch.sh
#
# Option 2. DO NOT WORK
# main.go:5:2: no Go files in /root/go/src/github.com/sugarme/gotch
#
#RUN export GOTCH_TEST_DIR="/tmp/gotch-test" \
#    && mkdir $GOTCH_TEST_DIR \
#    && cd $GOTCH_TEST_DIR \
#    && go mod init "github.com/sugarme/gotch-test" \
#    && go get -d "github.com/sugarme/gotch@v0.5.0" \
#    && rm -rf $GOTCH_TEST_DIR
#
# Option 3. Starts building but returns linking errors after a while:
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dsbrdbn'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zlaeh2'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_zd_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zimatcopy_square_t_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_claeh2'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaeh2'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_d_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed2'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_zhbrdbn'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_s_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_comatcopy2_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaeh2'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_sc_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_cs_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_dlaed3'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_z_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed3'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_cimatcopy_square_t_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_z_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_c_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_ssbrdbn'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_trans_mkl_zomatcopy2_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_dz_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_s_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_forward_d_out_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_dft_compute_backward_c_par'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_chbrdbn'
#/usr/bin/ld: /usr/local/lib/libtorch/lib/../lib/libtorch_cpu.so: undefined reference to `mkl_lapack_slaed2'
#
RUN go get -d "github.com/sugarme/gotch"
COPY lib.go.txt "$GOPATH/pkg/mod/github.com/sugarme/gotch@v0.5.0/libtch/lib.go"
COPY lib.go.txt "$GOPATH/src/github.com/sugarme/gotch/libtch/lib.go"
RUN ldconfig
COPY test.go.txt /home/main.go
WORKDIR /home
RUN go build main. go
ENTRYPOINT bash
```
[test.go.txt](https://github.com/sugarme/gotch/files/7771627/test.go.txt)
[lib.go.txt](https://github.com/sugarme/gotch/files/7771628/lib.go.txt)

Are there any considerations on how to avoid these errors?

**Comment by sugarme** [comment] 2022-01-08 08:42
Hi @ceo-domido ,

Sorry for the delay response.
Can you share your dockerfile? 

I don’t have a docker file for libtorch 1.10 but here is 1.7 version for amd64/cpu. 

`

FROM ubuntu:18.04

# Install dependencies
# ====================
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  curl \
  unzip

# Install Libtorch - CPU
#=======================
WORKDIR /
RUN curl https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.7.0%2Bcpu.zip --output libtorch.zip \
    && unzip libtorch.zip -d usr/local/lib \
    && rm libtorch.zip

RUN ldconfig

ENV GOTCH_LIBTORCH="/usr/local/lib/libtorch"
ENV LIBTORCH="/usr/local/lib/libtorch"
ENV LIBRARY_PATH="$GOTCH_LIBTORCH/lib"
ENV CPATH="$GOTCH_LIBTORCH/lib:$GOTCH_LIBTORCH/include:$GOTCH_LIBTORCH/include/torch/csrc/api/include"
ENV LD_LIBRARY_PATH="$GOTCH_LIBTORCH/lib"

`
 
Please let me know how you go?

**Comment by ceo-domido** [comment] 2022-01-10 17:19
Hi @sugarme ,
Dockerfile in attachment. It is mostly the same as you provided but mkl linking errors still appear.

[Dockerfile.txt](https://github.com/sugarme/gotch/files/7840620/Dockerfile.txt)

**Comment by maaft** [comment] 2022-02-16 08:42
Same thing happening after (successfull) installation of gotch and doing `go get github.com/sugarme/gotch` in my module afterwards:

1. install gotch GPU version as per readme (no errors)
2. go mod init test
3. go get github.com/sugarme/gotch --> linker errros

Or am I doing something wrong when adding gotch to my go module?

**Comment by sugarme** [comment] 2022-02-16 12:58
@maaft , 

Can you share the error log, your cuda and cudnn version please?

**Comment by iammeizu** [comment] 2022-02-17 02:56
met the same problem, cuda:11.4, cudnn:8
I have try all the ld flags in libtorch lib, but the problem still exist.

**Comment by sugarme** [comment] 2022-02-17 03:06
@iammeizu,
Can you share output of `nvidia-smi` and `nvcc --version` please? It might relate to `libtorch` library by itself. 
I set my boxes at nvidia driver 470.74, cuda 11.4 and libcudnn8_8 for cuda11.1 and they are all running Okay now .

Here is my nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0

**Comment by iammeizu** [comment] 2022-02-17 03:14
nvidia-smi:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:5E:00.0 Off |                    0 |
| N/A   48C    P0    41W /  70W |    162MiB / 15109MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

nvcc:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

**Comment by iammeizu** [comment] 2022-02-17 03:17
by the way, I have build my cgo project success in centos8, but failed in ubuntu18.04, so I supposed some dependent lead to this problem

**Comment by sugarme** [comment] 2022-02-17 03:38
@maaft ,

Thanks for the feedback on Centos8. We have google colab setup with gotch on ubuntu18.04 running fine with libtorch 1.9. 
Would you like to try it on libtorch 1.10 to see how you go and compare?
Here is the colab for 1.9: 
https://colab.research.google.com/drive/1-h57jZ46BeYuCQEpr1UpdjUDhkDlwWMW

**Comment by iammeizu** [comment] 2022-02-17 03:58
Thks for your patient, I have used libtorch 1.8 to aviod this problem, 
I will not research libtorch 1.10 in ubuntu18.04, cause I was not use gotch right now, I have my own golang inference project.
I stared gotch, and will use in the future. good job !

**Comment by sugarme** [comment] 2022-03-09 10:55
@ceo-domido , @iammeizu , @maaft 
I now can setup a Ubuntu 20.04 machine and reproduce the issue. It seems to be related to [missing mkl linking at Pytorch](https://github.com/pytorch/pytorch/issues/72653) and occurs with `gcc` linker. I tried with `clang` and can compile. So for now, a solution would be using `clang` compiler. If you use Ubuntu, that would be:
1. Install clang: `sudo apt install clang`
2. Set `CC` to use `clang` at `.bashrc` file
- `export CC=clang`
- `export CXX=clang++`
The issue should be fixed at the next Libtorch version (1.11).

**Comment by maaft** [comment] 2022-03-09 13:01
Thank you for the fix. Just to be clear, you compiled libtorch from source using clang?

I think I'll wait for 1.11 though. Any estimates on how long you will need to update gotch to 1.11?

**Comment by sugarme** [comment] 2022-03-09 22:07
@maaft ,

Not compiling libtorch but `clang` for CGO to compile binding to libtorch. I haven't touched on 1.11 but if no major changes, we will keep update accordingly.

As issue solved, I will close for now.

**Closed by sugarme** 2022-03-09 22:07 UTC

**Comment by maaft** [comment] 2022-03-11 22:56
Pytorch 1.1 has been released ;)

**Comment by Arnold1** [comment] 2023-01-20 12:57
@ceo-domido can you share you fully working docker file incl. main.go?
